---
title: "Untitled"
output: html_document
date: "2022-09-16"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir='C:/nexus/biz/potential_biz/portfolio/charts/charts')

```



```{r}

library(rgdal)
library(broom)
library(ggplot2)
library(svglite)
library(tidyverse)
library(maptools)
library(raster)
library(rgeos)

```


```{r}

# load shape files

download.file("http://naciscdn.org/naturalearth/packages/natural_earth_vector.zip",
              "data/zips/world maps.zip")



```


```{r}

unzip("data/zips/world maps.zip",
      exdir = "data/zips/Raw maps from zip")

```


```{r}

library(sf)
library(tidyverse)
library(ggplot2)

# world = read_sf(dsn   = "data/zips/Raw maps from zip/110m_cultural",
#                 layer = "ne_110m_admin_0_countries")

world = readOGR(dsn   = "data/zips/Raw maps from zip/110m_cultural",
                layer = "ne_110m_admin_0_countries")

world

```


```{r}

# sort(names(world@data))

# world@data %>% 
#   select('NAME', 'CONTINENT') %>% 
#   arrange(NAME)


world@data <- world@data %>% 
  mutate(CONTINENT = if_else(NAME == 'Russia', 'Asia', CONTINENT))

```




```{r}

# Reshape the world data so that polygons are continents not countries
world_id    = world@data$CONTINENT
world_union = unionSpatialPolygons(world, world_id)

```

```{r}

world_fortified = tidy(world_union, region = "CONTINENT")

# Here I create some dummy survey results
results = data.frame(id             = c("Africa", "Asia", "Europe", "North America", "Oceania", "South America"),
                     kpi            = c(20, 30, 50, 50, 60, 70),
                     continent_long = c(15, 80, 20, -100, 150, -60),
                     continent_lat  = c(15, 35, 50, 40, -25, -15),
                     stringsAsFactors = F)


```




```{r}

# Combine world map with results and drop Antarctica and seaven Seas
world_for_plot = world_fortified %>%
  left_join(., results, by = "id") %>%
  filter(!is.na(kpi))



```



```{r}

# Let's create the plot first wit data and let's care about the labels later
plain <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "transparent"),
  plot.background = element_rect(fill = "transparent"),
  plot.title = element_text(hjust = 0.5)
)

```


```{r}

# This is the actual results plot with different colours based on the results
raw_plot = ggplot(
  data = world_for_plot
  , aes(x = long, y = lat, group = group)
  ) +
  geom_polygon( #fill = 'red'
    aes(
      fill = kpi
      )
    ) +
  coord_equal(1.3) +
  scale_fill_distiller(palette = "RdYlGn", direction = 1) +
  labs(fill = "kpi") +
  plain

raw_plot

```


```{r}

mtrc = tibble(
      mtrc = world_for_plot %>% dplyr::select(id) %>% dplyr::distinct() %>% arrange(id) %>% pull()
    ) 
  

mtrc

```


```{r}




ggplot(
  data = world_for_plot
  , aes(x = long, y = lat, group = group)
  ) +
  geom_polygon( #fill = 'red'
    aes(fill = id)
    , show.legend = F
    # fill = "red"
    
    ) +
  coord_equal(1.3) +
  scale_fill_discrete() +
  labs(fill = "kpi") +
  plain


```













```{r}

## Now automatically adding label positions form the shapefile

# We start with getting the centroid positions of each continent and delete the continents we don't have
position = coordinates(world_union)

position = data.frame(position, row.names(position))
names(position) = c("long", "lat", "id")

position = position %>%
  filter(id %in% world_for_plot$id)

```

```{r}

# We can now refer to this new data in our previously created plot object
final_plot = raw_plot +
  geom_text(data = position,
            aes(label = id,
                x = long,
                y = lat,
                group = id))

final_plot

```

```{r}


final_plot = raw_plot +
  geom_text(data = results,
            aes(label = id,
                x = continent_long,
                y = continent_lat,
                group = id))

final_plot

```




```{r}

continents = world %>%
  group_by(CONTINENT) %>%
  summarise(.)

```






